### ISSUE TITLE
Barrel icon missing from sign GUI

### ISSUE THREAD

**Issue by clarfon** [jpanther/Dectorio#109]
I'm playing with the latest version of the mods:

* auto-research
* AutoDeconstruct
* Bottleneck
* creative-mod
* Dectorio
* Enhanced_Map_Colors
* textplates

Basically, empty barrels don't show up at all in the list of items.

**Comment by jpanther** [comment]
Thanks for the report. This is actually by design due to the way the base game handles auto barrelling. It ends up creating a heap of virtual barrels and these don't have 'normal' icons, which in turn breaks the sign logic. My workaround was to simply prevent barrels from being included in the sign icon selection. I can possibly see if I can get it to work for one single barrel icon, but I figured it wasn't worth the effort at the time. I'll take another look for you to see if it's something I can fix.
