### ISSUE TITLE
Conflicts with Alien Biomes

### ISSUE THREAD

**Issue by HercMighty** [jpanther/Dectorio#121]
Error ModManager.cpp:1323: Failed to load mod "Dectorio": __Dectorio__/data-updates.lua:3: __Dectorio__/prototypes/third-party/alien-biomes.lua:132: attempt to perform arithmetic on field 'count' (a nil value)
stack traceback:
	__Dectorio__/prototypes/third-party/alien-biomes.lua:132: in main chunk
	[C]: in function 'require'
	__Dectorio__/data-updates.lua:3: in main chunk
stack traceback:
	[C]: in function 'require'
	__Dectorio__/data-updates.lua:3: in main chunk

**Comment by jpanther** [comment]
Thanks for the report. I'll look into it.

**Comment by Deadlock989** [comment]
Hi there, this might be triggered by Industrial Revolution, which is trying to actively support Dectorio (but is less bothered about Alien Biomes right now).

alien-biomes.lua:132 is assuming that the minable property of trees has a result property and a count property. But there's a valid alternative way to define minable results, and that's with the results property, which is a table of multiple results. Industrial Revolution replaces result and count with results. If results is defined then result and count are most likely nil, which is triggering the arithmetic fail.

**Comment by jpanther** [comment]
Ah thanks for the extra info @Deadlock989, I'll look into changing the way the _Alien Biomes_ & Dectorio integration works so that it doesn't break in this instance.

As an aside, great work on your _Industrial Revolution_ mod, it looks great! If you have any compatibility problems with Dectorio be sure to let me know!

**Comment by Deadlock989** [comment]
Thank you. I wanted to make sure it fits in with Dectorio because Dectorio was a compulsory install for me during the 0.15-0.16 Factorio era. Adding compatibility was relatively easy, partly because of the way you structure your code. Cheers.

**Comment by jpanther** [comment]
This has been fixed in the next release of Dectorio (0.9.15) so that it will now properly test for `minable.results` or `minable.result` and also correctly handle the different variations within those two structures.

**Comment by dbeckwith** [comment]
I'm getting another error from Industrial Revolution that I believe is related to Dectorio.
[factorio-current.log](https://github.com/jpanther/Dectorio/files/3593348/factorio-current.log)

**Comment by jpanther** [comment]
@dbeckwith I have a feeling that is caused because you are running _Alien Biomes_ with _Industrial Revolution_. I don't believe those two mods are compatible yet so try again without Alien Biomes and see if you still have the issue.

**Comment by Deadlock989** [comment]
@dbeckwith jpanther is right, this does look like an issue caused by IR's support for Dectorio not taking Alien Biomes into account. IR doesn't "officially" support AB yet, but it generally works pretty well with IR. Because the issue is being tripped by IR's support for Dectorio, I would like to fix it. Could you do me a favour and report it on the IR mod portal page? Many thanks.

**Comment by dbeckwith** [comment]
[Done](https://mods.factorio.com/mod/IndustrialRevolution/discussion/5d77a081200ab7000d41c9de)! Thanks both of you for making great mods!
