### ISSUE TITLE
Landfill moved down the tech tree with Industrial Revolution

### ISSUE THREAD

**Issue by StephanSteinert** [jpanther/Dectorio#127]
Hi,

in the Industrial Revolution mod Lanfill i a red science tech but with Dectorio installed it's moved after explosives.

Can you please have a look at it?

Cu, steinio.

**Comment by jpanther** [comment]
Thanks for the report. I don't think I see a bug here as all Dectorio does is move Landfill to be under the Landscaping technology. From what I can tell it is appearing under Explosives because the _Industrial Revolution_ mod is placing it there as part of its technology tree overhaul. Unless you're seeing something I'm not?

**Comment by jpanther** [comment]
I've come up with a solution that will hopefully make this tech progression a little smoother. Landfill and Earthworks are now split into seperate technologies in Dectorio. This increases the net research cost but means that you can research Landfill earlier as it no longer inherits the Explosives dependency when overhauled by _Industrial Revolution_.

This change will be included in the next release.
