### ISSUE TITLE
Blueprints containing hazard-concrete incompatible with this mod

### ISSUE THREAD

**Issue by DRY411S** [jpanther/Dectorio#13]
Blueprints that contain the hazard-concrete-right tile will not import correctly when using this mod.

Vanilla aspects of the game really shouldn't break when using mods. Could you not continue to support hazard-concrete in your mod please?

**Comment by jpanther** [comment]
Thanks for the report. This is expected behaviour given the way the mod currently handles the vanilla hazard concrete but I agree that this is a poor experience. You can workaround this by setting the flag `["disable_hazard_concrete"] = false` in the config.lua and perhaps the solution is for me to make that the default state. In any case, I'll see if I can implement it in a less-destructive way.

**Comment by jpanther** [comment]
I've been doing some testing of this and interestingly noticed that hazard-concrete-left works fine, and it's only when trying to import hazard-concrete-right that it has this issue. The strange part about that is they are both handled the same way in the code so I can't see why one would break and not the other.

**Comment by DRY411S** [comment]
The more I think about this, and the clunky solution we have come up with to issue #19, the more convinced I am that you just leave the vanilla hazard-concrete alone as much as possible. Sure, you could change the graphic it uses, and the recipe to include iron-sticks, but why not leave it as researchable where it is, and have your other painted concretes as an 'add-on' to vanilla?

**Comment by jpanther** [comment]
Well it certainly would make things a lot simpler. I can't understand why this blueprinting issue is happening with only one rotation of the tile!

**Comment by jpanther** [comment]
Okay I've finally managed to track this down. Turns out the `next_direction` property of the tile is what it is referring to when importing the blueprint and I was setting that to use the painted concrete variant. In reality this property doesn't need to be changed because you can't place the hazard concrete with the mod installed so you never need to worry about what the next direction is.

**Comment by DRY411S** [comment]
Good to know that you've found the cause of the error message.

HOWEVER, now that you have, it just means that importing blueprints that contain hazard-concrete will fail silently.  :) The import will appear to have worked, but all the hazard-concrete will be lost from the blueprint.

I'd encourage you again to leave hazard-concrete unchanged, or change your mod so that the default is that it is not disabled.

**Comment by jpanther** [comment]
It does actually import correctly because the item for hazard concrete is still present, so it's not really failing at all.

**Comment by DRY411S** [comment]
Sorry, my last comment was badly written. Yes it imports, and the hazard-concrete is included, but parts of the blueprint are lost when it is placed in games where your mod is active and hazard-concrete is disabled. 

I'm not convinced that it's desirable for a mod to completely disable a vanilla tile and screw with blueprints like this. I think  people understand the risks of including non-vanilla items in blueprints, but losing vanilla parts seems undesirable to me.

**Comment by jpanther** [comment]
I do agree, although I think it's also a confusing experience to have 2 different hazard concretes available. Maybe a better solution is to remove the modded hazard concrete, move the vanilla hazard concrete tech under the painted concrete and swap out the graphics so they don't take on the vanilla look. The downside here is that people lose the option to keep the base hazard concrete.

**Comment by DRY411S** [comment]
Or just leave the hazard-concrete where it is, but with the recipe and graphics altered when your mod is active? My 'beef' is not with the recipe or the look, it's just that a vanilla tile goes missing.

**Comment by jpanther** [comment]
Yes but if I leave it where it is, you'd need to know which item to craft because there'd be 2 hazard concretes in the crafting menu that look identical but are actually separate tiles when placed and that is way more confusing. Maybe it's as simple as renaming the vanilla one to "Hazard Concrete (Vanilla)" or something and letting it keep the vanilla look and feel. I suspect that others who requested I add the option to keep the base item were due to the fact they liked the original graphics. That way the painted one is still its own entity and the two exist side by side with slightly different looks.

**Comment by DRY411S** [comment]
Why would there be 2 hazard-concretes? Just deprecate yours, but keep your extras?

Maybe people who suggested you keep the vanilla item thought that it was the only way they could avoid errors like in this issue, rather than liking the graphics better. Personally, I'd happily accept the new graphics and recipe on vanilla as an acceptable compromise to retain the vanilla item but make it 'fit' with the rest of the mod.

At the end of the day, it's your mod, and your decision, and I won't say any more. :)

**Comment by jpanther** [comment]
Haha, I actually find this discussion useful to think it through. I've been keen to work out the best solution to this as it seems to cause the most issues for people. Deprecating mine is basically what I was suggesting earlier by removing the item that crafts the modded concrete and simply moving the vanilla item under painted concrete with the new graphics. That way it places the hazard-concrete tile but it looks like the modded one. And then if someone removes the mod it will fallback to the correct tile rather than being removed. I guess I'll do that. It's impossible to please everybody but I do agree that the overarching idea that the vanilla stuff shouldn't break is definitely more important.

**Comment by DRY411S** [comment]
OK, so the final, final comment from me.

If people asked for vanilla to be kept it *might* actually have been because they already had assemblers in their factory and didn't like that they wouldn't work any more, rather than graphics. So perhaps keep the vanilla hazard-concrete, and have a 'switch' to let people keep the vanilla recipe and graphics. So it's a 'modify' switch rather than a 'disable'?

**Comment by jpanther** [comment]
Yup, way ahead of you. Already repurposed the config setting to do just that.
