### ISSUE TITLE
An option to split Dectorio items into multiple categories, to reduce crafting menu height

### ISSUE THREAD

**Issue by KironaDragryph** [jpanther/dectorio#210]
I'd love to have the option to split Dectorio crafting options into multiple categories, mainly because once everything is unlocked the inventory/logistics/crafting menu takes up my entire screen, and for the most part is dead space apart from when I'm specifically looking at Dectorio recipes. As it is, once the Dectorio technologies are researched, it effectively moves the entire menu to the top of the screen rather than being near the center.
![screenshot](https://user-images.githubusercontent.com/31082532/137249235-a3a78bf5-34d8-48d4-b0a3-5e765d9ba40f.png)

**Comment by jpanther** [comment]
Thanks for the suggestion. I think that you will find that this will happen even if the items are split up because of the sheer number of landscaping options. Dectorio does already include an option to move the items under the other tabs which may help. But really the way to avoid this is to turn off the Landscaping tools if you don't use them.
