### ISSUE TITLE
Missing Chain-Link Shadow

### ISSUE THREAD

**Issue by abordoli** [jpanther/Dectorio#23]
![image](https://user-images.githubusercontent.com/8505957/28908681-dce1aa66-77f2-11e7-9e4f-7ed6d61091d0.png)

**Comment by abordoli** [comment]
Bottom part is perfect. Top part has no shadow where one would logically exist, no?

**Comment by abordoli** [comment]
![image](https://user-images.githubusercontent.com/8505957/28909381-45862ba2-77f6-11e7-9d34-9430b0ef5603.png)

Horizontally, all is fine...

**Comment by jpanther** [comment]
I do know why this is happening and I'll have to see if it's possible to fix easily. The base game walls work around this problem because they are bulky enough to hide the gap. Unfortunately with the narrow chain-link fence, it looks odd in the situation you have demonstrated there. I'll have a play with some options.

**Comment by jpanther** [comment]
Closing this issue as it's not possible to fix within the limitations of the base game.
