### ISSUE TITLE
Factorio 2.0 Support?

### ISSUE THREAD

**Issue by lilac-eclipse** [jpanther/dectorio#243]
Hi!

I just wanted to know if you will update your mod for factorio 2.0 or if this is no longer supported?

Thanks!!

**Comment by jimmyG1** [comment]
cool i was beet to asking

**Comment by disheartenDEV** [comment]
+1 Please update for 2.0, This mod is awesome!

**Comment by hardyard-4201** [comment]
just made a github account only to join the request for an update. Your mod is really amazing. I can't imagine playing 
Space Age with out it. Please update it!

**Comment by JimBad05** [comment]
Adding another vote for updating Dectorio! I know nothing about GitHub and made an account just to request this. I'm really missing the lawn mower right now. Also it's kinda funny, all the colored hazard concrete didn't make the transition to 2.0 since Dectorio wasn't compatible, so it reverted all those patches to green grass. I just have random green spolotches where hazard concrete should be.

**Comment by VanillaIceCube** [comment]
Would absolutely love a 2.0 port! One of my favorite mods!

**Comment by SirMishaa** [comment]
Maybe a fork wouldn't ask too much work to do, I'm not sure if there are a lot of breaking changes

**Comment by Fr-Dae** [comment]
+1

**Comment by jpanther** [comment]
Thanks for the support everyone, I didn't realise the mod was still so popular! I'll see if I can work on a build for Space Age for you all.

**Comment by jpanther** [comment]
I've pushed v0.13.0 to the mod portal. Have a go and if you spot any problems please open issues so I can fix them up. I haven't had a lot of time to do testing but it seems to work well on my test saves.

**Comment by VanillaIceCube** [comment]
Absolutely consider it core for myself! I have a basetour episode I shot a while back and my base just looks absolutely gorgeous cause of it!

https://www.youtube.com/watch?v=XCvq1H2OVWs
