### ISSUE TITLE
Suggestion: add diagonal painted concrete

### ISSUE THREAD

**Issue by Yousei9** [jpanther/Dectorio#25]
Could you add diagonal wedges to hazard/painted concrete when placed on concrete?

![2017-08-10-10-32-52-3603322](https://user-images.githubusercontent.com/8436934/29161639-4d1b025e-7db7-11e7-8eed-299dd6480a33.jpg)

**Comment by jpanther** [comment]
Thanks for the suggestion. While it seems like an anomaly, this behaviour is actually on purpose. The reason is that the game prefers to have all the concrete types on one the same layer so that it knows how to render them correctly. The way the game is written, if you place them on a different layer (like the hazard concrete and stone path are on the right of your image) when you then try to place hazard concrete on top of concrete you end up with unpredictable behaviour. This particular issue was discussed in Friday Facts 179 (see https://www.factorio.com/blog/post/fff-179 at the end of the post).

You'll see in the examples on that page, the unpredictability makes for some very undesirable tile transitions when you place normal concrete and hazard concrete alongside each other. As a result, Dectorio keeps the base game behaviour by putting the various concretes on the same layer. The trade-off is, of course, you don't get the nice diagonal lines between the various concretes. Hopefully they'll address this in a future version of the game so that the tiles can merge happily without clashing.

**Comment by Yousei9** [comment]
I know why they did it, but I don't agree with castrating hazard concrete like that just because of some randomly colored borders.
I'd appreciate if you where to add back the old behavior regardless of what the devs think looks better as startup or config option. 99% of my hazard concrete is set up to use diagonal patterns to generate nice looking corners.

**Comment by jpanther** [comment]
I'm happy to make it configurable. I know it does work when it's on its own layer, although the current textures aren't ideal as it expects to be layered on the ground and looks a bit raised up when placed on top of normal concrete, but it will correctly draw the diagonals if you're happy with the tradeoff. What I might need to look at as a longer term solution is to make the painted concrete more like a flat texture that is literally 'paint' that needs to be applied to normal concrete, rather than it being it's own standalone item.

**Comment by jpanther** [comment]
I know this one took a while to sort out but in Dectorio 0.8.2 with Factorio 0.16, you can now place diagonal painted concrete tiles on top of other concrete types...

![screen shot 2017-12-19 at 15 49 38](https://user-images.githubusercontent.com/4462786/34141290-604f54fe-e4d4-11e7-9974-b2851f4c0435.png)

I'll go ahead and close this one for now. If you have any feedback, feel free to add it to this issue.

Ref: 34c034685be1d93c5e127025e27d31ce2851adf9

**Comment by Yousei9** [comment]
I was hoping you'd add a grid concrete back in.
There are some things that feel odd about it to me.

![2017-12-19-16-55-35-2134258](https://user-images.githubusercontent.com/8436934/34166028-20f8b50c-e4de-11e7-9c11-25ef9cccddf8.jpg)
- Randomly having 2x2 or 1x2 tiles kinda defeats the purpose of having a grid tile. Having randomly differing tile sizes also doesn't look industrial.
- Is there a technical reason why there's no diagonal border between grid concrete and normal concrete?
Not that I really mind, I'll probably use a painted between them anyway since it just looks better.
- Grid Concrete could look a bit different in map view to break up monotony of the base.

**Comment by jpanther** [comment]
Oh wow, that is definitely a bug, the random 2x2 and 1x2 is not meant to be happening! It seems to be only doing this when sprite resolution is set to high. If you set the settings to anything else it displays how I intend it to be. I'll create a new issue to track this one.

There's no real technical reason why the concretes are on the same layer so I can experiment with it a bit more and see if I can get it working nicely too. The new 0.16 stuff has some glitchy results merging tiles sometimes and so getting the hazard one to draw correctly was my priority. I'll reopen this issue to track the diagonal merging.

I'll adjust the map view colour too.

**Comment by jpanther** [comment]
I did a bit of experimenting and despite this initially not seeming to work, it turns out the devs added a new property to the tile prototype that allows this to be fixed (`transition_overlay_layer_offset`). Basically it allows you to correct for cases when the tile you are merging (ie. painted concrete) is not exactly one tile above the tile you are merging into (ie. concrete). By changing the offset you can have the two concrete variants on different layers and it will still draw all the merges correctly. I think I've tried to test every combination of layering in the mod and it looks pretty good to me!

![screen shot 2017-12-20 at 10 49 58](https://user-images.githubusercontent.com/4462786/34184409-b252afd6-e573-11e7-848a-8da2567d37ca.png)

**Comment by Yousei9** [comment]
Thanks for the quick update. 
Now grid concrete looks really nice in hr. Time to start ordering my bots to convert all existing concrete.
