### ISSUE TITLE
"Attach Notes" and signal colours conflict

### ISSUE THREAD

**Issue by GuiltyNeko** [jpanther/Dectorio#54]
https://mods.factorio.com/mods/321freddy/attach-notes

When running both mods, I get an error on startup referencing line 17 of the prototypes>signals>signals.lua file. I don't know what the issue is, but I'd be grateful if you could find & resolve it.

**Comment by curiousinternals** [comment]
The exact error I get is:
```
Failed to load mods: __Dectorio__/data.lua:56: __Dectorio__/prototypes/signal/signals.lua:17: attempt to index field 'order' (a number value)
```

I think the issue is with Attach Notes. It appears to be creating some virtual signals with numerical order fields when those fields really should be strings. See [this function](https://github.com/321freddy/attach-notes/blob/85038e4354c3c7e2fe4b62034c6c49322e838334/attach-notes/attach-notes_0.1.0/prototypes/icons.lua#L16).

That said, I'm wondering why this is being done by Dectorio ([prototypes/signal/signals.lua:17](https://github.com/jpanther/Dectorio/blob/0dbd98945986ae1bb91330482d5d1ccf61a7ece9/prototypes/signal/signals.lua#L17)):
```lua
if signal.order:find("colors") then
```
Instead of something like this:
```lua
if signal.subgroup == "virtual-signal-color" then
```

**Comment by jpanther** [comment]
Thanks for the report and PR. It was being done the `order:find` way as that's how Klonan had done it in one of his mods and so it seemed like a good method to use as I figured he'd know the impact behind the scenes. I haven't had a chance to test your change yet but at first glance it doesn't seem to actually test the color itself, only the subgroup. How does it know from the subgroup that the ones it is removing are the duplicates and not just every signal that matches that subgroup?

**Comment by jpanther** [comment]
Okay, I've tested the PR now and it does function as intended. I can't see any reason why the test was on the order value and so it appears safe to change it to the subgroup value instead. I'll merge the changes in.

**Comment by curiousinternals** [comment]
@jpanther 
> at first glance it doesn't seem to actually test the color itself

Neither does the code I replaced. I didn't know what the nature of the conflict was, so I made the assumption that all virtual signal colors are conflicting because that seemed to me to be what the code I replaced was looking for. Now I've dug a little further I think my assumption was wrong and I think the code I replaced was also doing the wrong thing.

Take a look at [these old changes](https://github.com/jpanther/Dectorio/commit/a5742a8cb5d9c006f82536f2ca09731ee877514d#diff-0c7d55819fe7ca83643e80877a281a3c). It seems while cleaning up the code, the original logic got slightly lost. While `signal.order:find("colors")` and `signal.subgroup == "virtual-signal-color"` _happen_ to match base virtual color signals, which is what Dectorio happens to need to modify, it also has the potential to match color signals added by other mods that have nothing to do with Dectorio's configured colors.

What the really old code was doing was the right thing: Only touching colors defined in `DECT.CONFIG.SIGNALS`.

**Comment by jpanther** [comment]
As I was going over your changes I realised the same thing, although hadn't gone back through the old commits to work out what had happened. I think I'll need to add in some additional checks to make this function as intended. The reason I moved to simply clearing out all the existing colours was due to the fact that there are were so many conflicts with other mods that just added lots of signal colours and it was causing startup crashes every time.

I'll reopen this issue for now and use it to track re-adding the proper checks to only edit the Dectorio signal colours.
