### ISSUE TITLE
Incompatibility with Land Mover when Dectorio is loaded second

### ISSUE THREAD

**Issue by legendblade** [jpanther/Dectorio#60]
When Dectorio and Alien Biomes are installed together (or any mod which Dectorio has a soft dependency on), Dectorio moves later into the load order allowing Land Mover by @LovelySanta (https://mods.factorio.com/mods/lovely_santa/LandMover / https://github.com/LovelySanta/FactorioMods) to act first, removing the landfill technology.

This causes Dectorio to fail to load due to there not being a landfill tech when https://github.com/jpanther/Dectorio/blob/develop/prototypes/technology/landscaping.lua#L48 is reached.

While I would say this is largely an issue on the part of Land Mover (it should have a soft dependency on Dectorio), Dectorio should probably check for the existence of the landfill technology before trying to modify its prerequisites.

Thanks.

**Comment by LovelySanta** [comment]
@jpanther The point of Land Mover is to remove the landfill made by stone, and there is a more complicated way to create the landfill (https://github.com/LovelySanta/FactorioMods/blob/master/source%20code/LandMover_0.1.3/data.lua#L65)

On that note, since you add waterfill afther the landfill research, if my mod would have Dectorio as dependency then the waterfill would be removed as well... I could just check all research and change dependency to landmover instead of landfill, but then i'm not even sure i would get all mods as i would need them all as dependency... Maybe if there is a way to make sure LandMover gets loaded as one of the last mods this sollution would work...

I would say let LandMover be an optional dependency on Dectorio, that way Dectorio can add waterfill onto the tech tree afther the landmover research? What do you think @jpanther ? What would be an optimal way to prevent this from happening with other mods as well?

Greetings
Lovely Santa

**Comment by LovelySanta** [comment]
@jpanther , @legendblade 
I solved the issue on my end:

I changed back the research name from landmover to landfill, so it just changes the way to obtain landfill..

That said... I fully soft coded all the stuff on the tech resulting in this code. So it will only change/delete the parts I mod, the rest will left unchanged, so it will be compatible with Dectorio and other mods:
```lua
data.raw.recipe["landfill"].enabled = false -- Disable landfill recipe

-- Edit the landfill research accordingly
local landfillTechnology = data.raw.technology["landfill"]

-- Edit the icon
landfillTechnology.icon = "__LandMover__/graphics/landmover_tech.png"
landfillTechnology.icon_size = 128

-- Disable the landfill recipe effect
for index, effect in pairs(landfillTechnology.effects) do
  if effect.type == "unlock-recipe" and effect.recipe == "landfill" then
    table.remove(landfillTechnology.effects, index)
    break
  end
end

-- Add the new recipe effects to create landfill
table.insert(landfillTechnology.effects,
  {
    type = "unlock-recipe",
    recipe = "landmover"
  })
table.insert(landfillTechnology.effects,
  {
    type = "unlock-recipe",
    recipe = "landmover-shovel"
  })

-- Add the required prerequisites
if not landfillTechnology.prerequisites then
  landfillTechnology.prerequisites = {}
end
table.insert(landfillTechnology.prerequisites, "concrete")

-- Edit the data.raw to updated landfill version
data.raw.technology["landfill"] = landfillTechnology
```

Conclusion: other mods will be able to rely on the ability to add landfill as a prerequisite. On your end I would suggest soft coding the prerequisites ( https://github.com/jpanther/Dectorio/blob/develop/prototypes/technology/landscaping.lua#L48 ).

I'll say this as solved on my end.

Greetings
Lovely santa

**Comment by jpanther** [comment]
Thanks for the initial report and detailed responses. I agree that your solution of not removing the vanilla tech is a much more robust one. One of the things I've learnt is that to maintain compatibility across mods, you really need to try to keep the vanilla things in place as much as possible and then just attach your modded stuff to them. That said, I've gradually gone through Dectorio over time and converted all the tech changes to softer versions but this one obviously slipped through. I'll adjust it to insert the prerequisite instead of replacing it and that should help prevent any other issues in the future.
