### ISSUE TITLE
Question about crowdin

### ISSUE THREAD

**Issue by dima74** [jpanther/Dectorio#72]
Thanks for nice mod!

Could you, please, say, how you uploaded strings (that is .cfg files) to crowdin (I know it should be rare action, but looks like you have done it few times)?

(because when I try to do so (for another project) crowdin says "file was imported as a .txt file, as its file format is not supported")

**Comment by jpanther** [comment]
The problem is that CrowdIn doesn't support .cfg files. You simply have to rename them .ini and it will import. Although whether it imports every string correctly is up to how the owner of the CrowdIn project has the project configured. You'll have to check they are correct after you import just to be sure.
