### ISSUE TITLE
Desync in MP when placing Steel Sign

### ISSUE THREAD

**Issue by Kyle1457** [jpanther/Dectorio#82]
Buddy found out when the Steel Sign is placed it causes all players to desync from the game. 
 Desync report is too large to attach and can be found here. https://www.dropbox.com/s/nndnrx6v6t5ysrc/desync-report-2019-03-03_00-56-21.zip?dl=0

**Comment by jpanther** [comment]
Thanks for the report. I'll take a look and let you know if I have any questions.

**Comment by jpanther** [comment]
I've been doing some testing and I'm able to reproduce the desync on your save. I'll need to do some more digging to work out exactly what is causing the issue. When I test using the same multiplayer setup but without the large modpack you're using, the desync doesn't occur.

**Comment by jpanther** [comment]
I've finally worked this out! Turns out it's an incompatibility with _Yuoki Industries_ where some of these modded items cause a problem when trying to load their icon. When Dectorio then tries to display the sign GUI for picking an icon, the game desyncs.

Due to the sheer number of items that mod is adding, I can't narrow down exactly which icons are tripping things up so I'm patching this in the next version of Dectorio by preventing all _Yuoki Industries_ items from appearing in the icon picker.

I've verified that this stops the desync on the save you provided.
